### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by MagicMarvMan** [Skuldur/Classical-Piano-Composer#5]
Hello,
When I'm executing predict.py using Keras' Theano backend, I always get an error like this:
```
Traceback (most recent call last):
  File "predict.py", line 134, in <module>
    generate()
  File "predict.py", line 25, in generate
    prediction_output = generate_notes(model, network_input, pitchnames, n_vocab)
  File "predict.py", line 92, in generate_notes
    result = int_to_note[index]
KeyError: 68 [or something similar, a.e. 143 or something else]
```
I switched to the theano backend, because TensorFlow gave me an error while installing.

I hope you can help me.

MagicMarvMan

**Comment by Skuldur** [comment]
Hi,
I have not used the Theano backend with the program before so I'm not sure what is causing the error.

However, I would recommend trying to get Tensorflow to work since Theano is no longer being supported by the developers.
